[profile.default]
src = "src"
out = "out"
viaIR= true
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.24"


[rpc_endpoints]
crossfi_testnet = "${CROSSFI_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
